// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interface.proto

package com.dahuatech.grpc.generate;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dahuatech.grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.dahuatech.grpc.Student student = 1;</code>
   */
  java.util.List<com.dahuatech.grpc.generate.Student> 
      getStudentList();
  /**
   * <code>repeated .com.dahuatech.grpc.Student student = 1;</code>
   */
  com.dahuatech.grpc.generate.Student getStudent(int index);
  /**
   * <code>repeated .com.dahuatech.grpc.Student student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .com.dahuatech.grpc.Student student = 1;</code>
   */
  java.util.List<? extends com.dahuatech.grpc.generate.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .com.dahuatech.grpc.Student student = 1;</code>
   */
  com.dahuatech.grpc.generate.StudentOrBuilder getStudentOrBuilder(
      int index);
}
