// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.dahuatech.grpc.generate;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dahuatech.grpc.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>optional string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
