namespace=cloudspace; function get() { docker ps | grep $1 | grep -v pause | grep -v sidecar; };
function to() { docker exec -it -u root -w / $(docker ps | grep $1 | grep -v pause | grep -v sidecar | head -n 1 | awk '{print $1}') /bin/bash; };
function getall() { kubectl -n ${namespace} get po; };
function getpod() { kubectl -n ${namespace} get pods -A -o wide | grep $1; };
function edtpod() { kubectl -n ${namespace} edit pod $1; };
function delpod() { kubectl -n ${namespace} delete po $1; };
function topod() { kubectl -n ${namespace} exec -it $(kubectl -n ${namespace} get pods | grep $1 | awk '{print $1}') -- /bin/bash; };
function watpod() { kubectl -n ${namespace} get pods -w -o wide | grep $1; };
function despod() { kubectl -n ${namespace} describe pod $(kubectl -n ${namespace} get pods | grep $1 | awk '{print $1}'); };
function toppod() { kubectl -n ${namespace} top pod; };
function logpod() { kubectl -n ${namespace} logs -f $(kubectl -n ${namespace} get pods | grep $1 | awk '{print $1}'); };
function getdep() { kubectl -n ${namespace} get deploy | grep $1; };
function edtdep() { kubectl -n ${namespace} edit deploy $1; };
function getsts() { kubectl -n ${namespace} get sts | grep $1; };
function edtsts() { kubectl -n ${namespace} edit sts $1; };
function getsvc() { kubectl -n ${namespace} get svc | grep $1; };
function edtsvc() { kubectl -n ${namespace} edit svc $1; };