// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interface.proto

package com.dahuatech.grpc.generate;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dahuatech.grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.dahuatech.grpc.Student student = 1;</code>
   */
  boolean hasStudent();
  /**
   * <code>optional .com.dahuatech.grpc.Student student = 1;</code>
   */
  com.dahuatech.grpc.generate.Student getStudent();
  /**
   * <code>optional .com.dahuatech.grpc.Student student = 1;</code>
   */
  com.dahuatech.grpc.generate.StudentOrBuilder getStudentOrBuilder();
}
